name: Sync Synextra HQ detections

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Sync detections
        env:
          FALCON_CLIENT_ID: ${{ secrets.FALCON_CLIENT_ID_SYNEXTRA_HQ }}
          FALCON_CLIENT_SECRET: ${{ secrets.FALCON_CLIENT_SECRET_SYNEXTRA_HQ }}
          FALCON_CID: ${{ secrets.FALCON_CID_SYNEXTRA_HQ }}
        run: python scripts/sync_detections.py rules/synextra-hq-rules.json
